### ISSUE TITLE
Participate in Mozilla 2019 Sprint for Internet Health

### ISSUE THREAD

**Issue by nohorse** [Hack4Eugene/SpeedUpAmerica#10]
SUA would be a great project for 2019 Sprint for Internet Health.  https://foundation.mozilla.org/en/opportunity/open-events-guide/about-the-2019-sprint-for-internet-health/

I'm a Mozilla Open Leaders mentor this season and it's time to start planning local events for the sprint.  SpeedUpAmerica would be a great focus project and help promote it on a larger scale.

I'm envisioning two events in the form of meetups.  One in the start of May and the other at the end of May.  Maybe hosted at IDX.  In the first event we'd set up this project for more contributors, set repo topics and issue labels to attract attention, etc.

I can sign us up today.
https://www.mozillapulse.org/add?tags=sprintforih,2019

@mattsayre  thoughts?

**Comment by ryanrolds** [comment]
More the merrier. By the first Mozilla Sprint event, we will probably already have plenty of tickets. The project has a `README.Docker.md` file should be merged into the `README.md` by H4C, so setup should be trivial (if you doubt the ease please look a the existing file). My point being, the Mozilla Sprint events can probably be all coding and no PM.

**Comment by nohorse** [comment]
@mattsayre wants to re-evaluate after the event.

**Comment by ryanrolds** [comment]
What is being re-evaluated after the event (I assume H4C)?

**Comment by csjoblom** [comment]
Two long weekends in a row might be a tough sell for those working on this challenge especially since they are already in the flow of things. No need to wait to continue in my opinion. Is there an intended goal for pigeon holing this into Mozilla stuff?

**Comment by ryanrolds** [comment]
A re-evaluation sounds like something that should be done by the governance group formed from maintainers/contributors.

**Comment by ryanrolds** [comment]
Are there any specific concerns? I would understand if the project doesn't get off the ground, but if the project is successful, I'm not sure what would need re-evaluation.

**Comment by ryanrolds** [comment]
@mattsayre, can you provide any comment on the need you're anticipating?

**Comment by antonioortegajr** [comment]
For the IDX location an IDX employee must be present. Here are the general guidelines for outside events at IDX: https://github.com/antonioortegajr/guest-events-at-idx This means if you plan something and no IDX employee can attend for whatever reasons, the event could not be at IDX and would have to find a new venue in the remaining time. This is a risk the python and cyber security groups have all acknowledged. Additionally if there is an IDX event planned, that will take priority. Again risk acknowledged. That being said a more guaranteed location is likely the better option.

As for a second hack-athon that would be another hackathon in town after like a week after the for a cause and the game one. As a promotion tool, this sounds a little oversaturated. Additionally I worry about dev burnout being that the devs working on this project will be hanging (I assume working) out at the for a cause.

**Comment by mattsayre** [comment]
My thought was simply that there be consideration for new contributors that would emerge at the hack. Specifically leaving room for others to weigh-in on the decision about connected sprint(s) dates & venue. I'm not saying that the Sprint isn't a good idea. I am saying that decision about date and location be made with everyone at the table - during or shortly after Hack for a Cause 2019.

**Comment by nohorse** [comment]
More info on the Mozilla global sprint:  https://www.meetup.com/EugeneTech/events/260713803/

Two easy meetup style events.  One to kickoff and one to wrap-up.  I'll get more information as we get close, but this is really a low-key "sprint" and more of a way to highlight projects.  There will be a few local projects like an innovation-asset open-data project and whatever folks bring to the launch event.  Participation is of course totally optional. I was encouraged to do this event as part of Mozilla Open Leaders program where I'm mentoring this cohort.  below is the "POP"


Purpose
To help local open source projects in Eugene, OR gain visibility and traction from the greater open source community.

Outcome
local open source projects are have clear paths to collaboration and have gained new collaborators.

Process
* Project maintainers bring open source projects to the launch event
* Presenters talk about things like readme's, contributor guides, milestones, issues and roadmaps.
* Projects add issues for missing bits and labeled with "global-sprint" and "open-eugene"
* Repo given topics of "open-eugene" and "global-sprint" to participate in the
* Project maintainers bring stories to the finishing event and share.

**Comment by antonioortegajr** [comment]
Closing since mentioned above:  "decision about date and location be made with everyone at the table - during or shortly after Hack for a Cause 2019."
