### ISSUE TITLE
Improve GitHub wiki pages to strengthen onboarding (1SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#111]
The pages we have good, but we would like to improve them further. The goal of these changes is to have a single root wiki page that provides an overview of the project, links to key documents, and links to a page on how to join the project and contribute. Go through all four wiki pages and update them to reflect changes in the project. Also, update the pages to contain information on the migrator repo and include a section on key documents and provide links to:

* https://docs.google.com/document/d/17NITV1HQCGGyqMRWvrxYkXYlvcYc4a3FT4taGSM71MQ/edit
* https://paper.dropbox.com/doc/SpeedUpAmerica-Moving-Forward-i3HsHg4UYWjHzXm2hvn62
* https://paper.dropbox.com/doc/SpeedUpAmerica-Big-Rocks--AeuVcs~j7dcgBMw5DowSqSz2Ag-c1sMe5n0iXr2fkc7d3K0T
* https://paper.dropbox.com/doc/SpeedUpAmerica-Infrastructure--AevPkP8D4dz3LtYQhBz7jt1kAg-q14UbYbhzyEM6mqaiN05d

We also want to provide links to the Hack4Eugene Slack Inviter and the name of our main Slack channel).

**Comment by Kourchenko** [comment]
https://github.com/Hack4Eugene/SpeedUpAmerica/wiki/Developer-OnBoarding-Start

**Comment by mattsayre** [comment]
One thing I did was our slack channel a default when you join, sorry I didn't mention that before. This inviter seems to work pretty well. Updating page with that.

**Comment by mattsayre** [comment]
Looks good, closing.
