### ISSUE TITLE
Create vector tileset for Census Tracts, upload to Mapbox, and document process (2SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#114]
We need to generate vector tilesets for Census Tracts.

Census Tract shapefiles: https://www2.census.gov/geo/tiger/TIGER2017/TRACT/
Instructions on using Tippecanoe to generate a vector tilset: https://github.com/mapbox/tippecanoe#selectively-remove-and-replace-features-census-tracts-to-update-a-tileset

Talk to Ryan about uploading to our Mapbox account when the task is complete. Use you're won free Mapbox account for development.

**Comment by Kourchenko** [comment]
https://paper.dropbox.com/doc/SpeedUpAmerica-Vector-Tilesets--Ae_Vs0m6bCOwqtbf35vyo4z2Ag-LKoxlUFlO2hCZycbjFaz5

Created Census Tracts for Oregon, FIPS Code 41
