### ISSUE TITLE
Add rel="noopener" to all links with target="_blank"

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#117]
This is a potential security & performance issue.

It's an easy fix, but we should decide whether to use just `rel="noopener"` or `rel="noopener noreferrer"`.

# Background

Short explanation: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
Some more detail, including the performance issue: https://medium.com/@ali.dev/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**TL;DR**

* By default, a page opened using `target="_blank"` shares some resources with the starting page and it can use `window.opener.location` to navigate the tab hosting the original page.
* Using `rel="noopener"` on such a link prevents this.
* Using `rel="noreferrer"` does the same and also prevents the browser from sending the `Referer` HTTP header when requesting the new page.
* Browser support for [noreferrer](https://caniuse.com/#search=noreferrer) goes back farther than for [noopener](https://caniuse.com/#search=noopener), so it's frequently recommended to use both: `rel="noopener noreferrer"`

# Question

"`noopener`" is the technically correct fix but its browser support doesn't go back as far as "`noreferrer`". **Do we care more about applying this fix to old browsers or about allowing referred sites to see that we sent traffic to them?**

**Comment by ryanrolds** [comment]
No objections from me about `noopener`. I don't' mind sending referrer info to partnered sites as they may be paying attention to who is sending them traffic. What browsers don't support `noopener`? I *don't* sites we link to are going to abuse it, but I don't see a reason to not close the attack vector.

**Comment by noahbrenner** [comment]
According to [Can I use](https://caniuse.com/#search=noopener), browsers without support for `noopener` and *with* support for `noreferrer` are:

* IE 11 (though `noreferrer` is only supported in later versions of Windows 10)
* Edge 13-18
* Firefox 33-51
* Chrome 16-48
* Safari 5-10 (support starts in 10.1)
* Opera 15-35
* iOS Safari 4-10.2
* Android Browser 2.3-4.4.4
* Blackberry Browser (all)
* Samsung Internet 4
* KaiOS Browser (all)

I'd guess the only ones likely to have enough use to care about would be IE, early Edge, and maybe old Safari.

I'd also prefer to keep the referrer header if other concerns don't override that.

Currently, the links we have with `target="_blank"` are:

* Sharing on Facebook, Twitter, and LinkedIn
* Our partners: City of Eugene, TAO, US Ignite, and M-Lab
* Our GitHub repo

**Comment by ryanrolds** [comment]
Looking at https://caniuse.com/usage-table, it looks like all of the browsers versions that don't support have very low usage numbers (like almost all are < 1%). Let's meet in the middle. For "partner" sites, only add `noopener`. For anything that is not a partner site we go the safe route and set both. Thoughts?

**Comment by ryanrolds** [comment]
Are we concerned that social media sites won't get referrer information? @mattsayre

**Comment by ryanrolds** [comment]
I want @bishoplafer's opinion on this too.

**Comment by noahbrenner** [comment]
That mix of safe and keeping the referrer for partner sites makes sense to me. It'll definitely be good to get Matt's and Bishop's thoughts.

**Comment by bishoplafer** [comment]
I think noopener is fine, sending the referral traffic to partner sites seems like something we should do. I am sure we want to know who our referrers are. It also seems to me that this is more of a vulnerability for traffic coming from a social media site as opposed to traffic we are sending away from SpeedUpAmerica.

**Comment by ryanrolds** [comment]
As I understand the vulnerability, it's a page opened by _blank changing the window that opened it through window.opener.location.

Check out https://mathiasbynens.github.io/rel-noopener/

**Comment by bishoplafer** [comment]
I read the article, so long as we are linking to reputable sites - I don't think it is much of an issue. What I meant was, if someone is trying to phish - it is more likely that they share a link or host one themselves. We don't have any malware on our site, so it isn't a security issue for us, rather a potential issue for our users. It seems like a pretty easy fix though.

**Comment by ryanrolds** [comment]
Unless someone objects, let's go with noopener only on all links using _blank.

**Comment by noahbrenner** [comment]
Sounds great, I'll take care of that now.
