### ISSUE TITLE
Fix using back button after a test preventing taking the test again (0.5SP)

### ISSUE THREAD

**Issue by nohorse** [Hack4Eugene/SpeedUpAmerica#124]
saw the notice to take the test on social media and so I did.  Then I wanted to take it again after testing my speed in other places.  hitting back and then trying again, the "let's do this" button doesn't pop up the test again.  refreshing the speed test page takes you back to the home page.  So it's a bit clunky.

**Comment by ryanrolds** [comment]
Fix deployed.
