### ISSUE TITLE
IPV6 address doesn't work with our submissions on "Take Speed Test"

### ISSUE THREAD

**Issue by Kourchenko** [Hack4Eugene/SpeedUpAmerica#126]
Taking the speed test on Firefox causes the test to err, and an error page to be rendered.
**Browser: Firefox**

Steps to recreate:
1) Navigate to Home Page
2) Take Speed Test, fill out questionnaire, and hit "Test My Speed"
3) When test completes, I receive a sucessful text response in the modal and then am redirected to an error page

---
name: Bug report
about: Create a report to help us improve
title: 'IPV6 Error'
labels: 'BUG, URGENT'
assignees: 'Kourchenko'

---

**Describe the bug**
Taking the speed test using Firefox causes the test to err, and an error page to be rendered. The cause is in getting IPV6 from https://jsonip.com/. No IP address is being recorded when the Submission is recorded, and an error is thrown.

**To Reproduce**
1. Navigate to Home Page
2. Take Speed Test, fill out questionnaire, and hit "Test My Speed"
3. When test completes, I receive a successful text response in the modal and then am redirected to an error page.

**Expected behavior**
The correct navigation for taking a speed test is that the questionnaire answers are recorded, the speed test data is recorded, and the users IP address is recorded. Then the user is navigated to "/all-results" where the Map is rendered.

**Desktop (please complete the following information):**
 - OS & Version: Windows 10 10.0.17134
 - Browser: Firefox Quantum 67.0.2

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Logs recorded using Loggly - error:IPAddr::InvalidAddressError: invalid address:

**Comment by ryanrolds** [comment]
Fixed by: https://github.com/Hack4Eugene/SpeedUpAmerica/pull/132
