### ISSUE TITLE
Constrain star rating UI to its container at all viewport widths (0.5SP)

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#130]
**Describe the bug**

On the 2nd page of taking the test, the row of rating stars extends to the right, outside of the outlined box containing the form. This is only an obvious issue when the viewport width is between 992px and around 1200px

**To Reproduce**
1. Go to the SpeedUpAmerica home page
2. Click on "Take the Test!!"
3. Select any type of internet connection and click "Let's do this!"
4. Change your viewport width to somewhere in the 992-1200px range (with Chrome dev tools open, your viewport size will be displayed as you drag the window edge).
5. Notice the rating stars extending outside the box to the right.

**Expected behavior**

The rating stars should remain contained in the box. This could be done by either scaling the stars along with the container or by fixing the size of the container. The container has a class of `col-md-6, and is sized to 50% of the screen width, so there's plenty of room to make it larger and have a fixed width.

**Screenshots**

![image](https://user-images.githubusercontent.com/24858379/59536589-f0603e80-8ea8-11e9-81ed-be523d492dff.png)

**Desktop (please complete the following information):**

 - OS & Version: Ubuntu 18.04.2 LTS
 - Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)

**Additional context**

The problem disappears on smaller viewports due to a CSS breakpoint.

**Comment by ryanrolds** [comment]
Solid bug report :)

**Comment by mattsayre** [comment]
As part of this, can we have consideration for moving to a 5 star system? That is what sanjose is using. Seems generally more consistent with cultural norms (ie 5 start hotel).

**Comment by ryanrolds** [comment]
No objections. We will need to write a database migration to adjust the ratings we have in the database.

**Comment by ryanrolds** [comment]
Don't worry about adjusting the number of stars. I will make another ticket for that as it requires a DB migration.

**Comment by JCoulter85** [comment]
I have found that if we choose to go the 5 star rout there isn't a resizing issue within the form [with stars spilling outside of the form field]. Please let me know if you would like me to solve the 7 star resize issue within the form, or just remove 2 of the stars and continue with that rout.

**Comment by ryanrolds** [comment]
Removing the two stars will require a DB migration that adjusts the current DB records that already collected ratings. There may also be math that depends on the previous number of stats. Please check all places that touch the ratings.
