### ISSUE TITLE
Revise M-Lab queries to use StandardSQL and current M-Lab BigQuery tables

### ISSUE THREAD

**Issue by critzo** [Hack4Eugene/SpeedUpAmerica#15]
`submissions_importer.rb` has [outdated queries](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb#L66-L133)to M-Lab BigQuery tables. Revise and test updated queries. Needed to resolve #2 

Table name should change from `plx.google:m_lab.ndt.all` to `measurement-lab.release.ndt_all`, and I'll work on revised queries to post here or in a PR.

**Comment by ryanrolds** [comment]
This has been handled by Chris R.
