### ISSUE TITLE
UI Feature - Notify User on Location Issue (1 SP)

### ISSUE THREAD

**Issue by Kourchenko** [Hack4Eugene/SpeedUpAmerica#171]
**Is your feature request related to a problem? Please describe.**
As a user, I want to know why my location isn't working properly on certain browsers, but is working on other browsers. A prompt appears on Chrome/Firefox for location services, but not on Safari/others. I want to know when it is an issue with my browser that I can fix, and when it is an issue with my previous denial of location permissions.

**Describe the solution you'd like**
Show the user with an additional message if we detect that their browser is Safari.
Show the user a reminder message if we detect that their browser is not Safari, but location privileges are denied.

**Describe alternatives you've considered**
Simply adding a `Safari Browser: Please Turn on WiFi and Location Services` message in our error modal popup would be sufficient, but additional information and browser detection is important.

**Comment by JCoulter85** [comment]
171 has been completed and merged. Looking good :+1:
