### ISSUE TITLE
Make sure we are setting client_application to speedupamerica (SP1)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#178]
Make sure we are setting client_application to speedupamerica for tests run through SUA. May requiring updating NDT JS library.

**Comment by ryanrolds** [comment]
Once updated, try setting `speedupamerica` for the setting found at https://github.com/m-lab/ndt-javascript/blob/master/src/ndt-client.js#L64. Don't adjust the library, when instantiating the client it should be possible to change that setting value.

**Comment by ryanrolds** [comment]
The NDT client has been updated. It's going to take some exploration to figure out how to get our client_applciation set.
