### ISSUE TITLE
Enhance Explore the Data, Internet Service Providers, to auto populate top 3 ISP’s (2SP)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#179]
Enhance Explore the Data, Internet Service Providers, to auto populate top 3 ISP’s for the defined statistical boundary. Where “top” is defined as median download speed. Include user’s ISP as a 4th ISP

**Comment by ryanrolds** [comment]
At this time we only have ZIP. In a future change, we will have boundaries. As part of this ticket also center the map and zoom it in near the user's locations.

**Comment by ryanrolds** [comment]
I added myself, Kirk and Diego to the assigns. We all worked on the PR and I think it should be divided three ways.

**Comment by ryanrolds** [comment]
This has been merged for testing.

**Comment by ryanrolds** [comment]
This has been released.
