### ISSUE TITLE
Update ISP list

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#18]
The ISP list needs to be expanded to include ISP in the PNW.

**Comment by khutchison** [comment]
I can do this - which file is the ISP list in?

**Comment by ryanrolds** [comment]
Hold on this. It may be auto-populated. If you wanted to look through the logic and confirm it's a static list we define that would be helpful.

**Comment by bishoplafer** [comment]
I will work on this issue.

**Comment by critzo** [comment]
I've pulled on the unique IP addresses in M-Lab results for the past year and am grabbing the ISP names from ipinfo.io

**Comment by benanamen** [comment]
The ISP list is not static. It is pulled from from the DB,  provider_statistics.name

**Comment by Amcclennahan** [comment]
@benanamen thanks for digging in here. Sounds like we need to consolidate our data, and then update it. 

1. Pull the ISP list from /app/helpers/home_helper.rb instead of provider_statistics.name
2. Update /app/helpers/home_helper.rb 

That resolves the issue you're describing, is that right?

**Comment by benanamen** [comment]
> That resolves the issue you're describing, is that right?
Well, that depends on if you want to keep hand editing the static list or just update the DB. The order you have would be for having a static list. Keep in mind, some place pull the static data, others pull from the DB.

I already posted the code to update the providers to pull from the DB which would be the better option.  (Issue #52)I just need to update it to sort Alphabetically unless someone else gets to it.

**Comment by Amcclennahan** [comment]
Fantastic. Sorry I'm catching up and as you commented here I was reading your other chain :) You guys are too fast!

I definitely don't think we should be hand updating anything and that absolutely can't scale, so it needs to be changed. What's the lift for that? If it's trivial than absolutely let's get it changed. 

Give me your gut on the lift and I'll prioritize accordingly

**Comment by benanamen** [comment]
If I understand what you mean by "lift", the list is copy pasting the code in #52 as it shows. Pretty sure the ordering would be set in file submissions_helper.rb line 65 at the get_list_values method. Looking into right now.

**Comment by Amcclennahan** [comment]
Well that sounds too easy! Any dissenting thoughts from anyone else here?

**Comment by ryanrolds** [comment]
I think this is done. Chris R gave Bishop the list and the db seed was updated. We have a PR that updates the list the UI is coming from by copying the list in the seed. We have another PR for generating the list from the DB.
