### ISSUE TITLE
Get BigQuery data loading and document process

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#2]
> For setup instructions look at [README.Docker.md](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/README.Docker.md). Once we have complete local environment setup instructions (a few tickets need to be finishing) we will update README.md.

Rails' is [configured to download upload & download data ever Sunday at 11:30pm](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/config/schedule.rb#L21). It should be possible to trigger the import logic with `docker-compose run frontend rake import_mlab_submissions`. Setup access to M-Lab's BigQuery database, see [BigQuery Quick Start Guide](https://www.measurementlab.net/data/docs/bq/quickstart/). It looks like credentials are already checked into the repo. Figure out how to set up your own credentials, but do not check them in. Please document setup instructions in `README.Docker.md`. If you have questions about BigQuery setup check with Chris Ritzo on H4C Slack.

Current output from running `import_mlab_submissions` task:
```
$ docker-compose run frontend rake import_mlab_submissions
Started job to import MLab speed test submissions
rake aborted!
NoMethodError: undefined method `created_at' for nil:NilClass
/suyc/app/classes/submissions_importer.rb:60:in `time_constraints'
/suyc/app/classes/submissions_importer.rb:84:in `upload_query'
/suyc/app/classes/submissions_importer.rb:52:in `import'
/suyc/lib/tasks/submissions.rake:13:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => import_mlab_submissions
(See full trace by running task with --trace)
```

The bulk of the logic for the task be found at:
*  https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/lib/tasks/submissions.rake#L8
* https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/app/classes/submissions_importer.rb#L48

**Comment by critzo** [comment]
One thing that could be considered is doing all of the M-Lab data aggregation and spatial joining within BigQuery. @georgiabullen has been working with the BigQuery GIS functions, joining M-Lab test results with geo areas, computing stats for each area, and generating tilesets. The end result is hosted tilesets (in Mapbox, or static assets in GCS) and front-end hosting. Our goal is to produce public tables for US geographies that are updated regularly with scheduled jobs.

**Comment by ryanrolds** [comment]
This is handled. Closing.
