### ISSUE TITLE
Update image used in social meta tags (0.5 SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#205]
**Is your feature request related to a problem? Please describe.**
The image used for Facebook is the old logo, we should use the new logo . Make sure the logo confirms to recommendations for the different social meta tags. 

**Describe the solution you'd like**
Update any social meta tags to use the new logo and make sure that the image used conforms to recommendations for that tag.

**Comment by coatsd** [comment]
I can do this one to dip my toes in.

**Comment by coatsd** [comment]
Do we want to keep the same color pallet as the last one?

**Comment by ryanrolds** [comment]
Are you thinking about making a new logo? We have an updated logo. If there are issues with the dimensions and what the different social media tags want we can see about getting a modified logo.

**Comment by coatsd** [comment]
Naa, I downloaded the Facebook and twitter logos from their brand websites. I just wanted to make sure we wanted the white versions. I already have a copy ready to be pushed to a new branch, I just need permission.

**Comment by ryanrolds** [comment]
Oh. I think we want to use our logo, not FB or Twitters.

**Comment by coatsd** [comment]
Oh, okay. Yeah, if you have a file, feel free to send it over so I can plug it in.

**Comment by coatsd** [comment]
Or is it in there?

**Comment by ryanrolds** [comment]
Check the images in the repo (app/assets/images/...) if there isn't a version that meets the requirements we can have one made.

**Comment by coatsd** [comment]
Yeah, there isn't another one in there.

**Comment by ryanrolds** [comment]
That meets the requirements? What are the requirements that are not met? Make a list of what we need and post it in the channel. We can get it taken care of.

**Comment by coatsd** [comment]
I'm confused. I thought we just wanted to use the new social media tag for Facebook because the one we had wasn't current. I personally don't see anything wrong with what we were using, but I thought it was just a minor update to the logo for aesthetics.

**Comment by coatsd** [comment]
I also thought the requirements were in reference to Facebook's kind of "terms of use" with their logos.

**Comment by ryanrolds** [comment]
The stopwatch image is the old logo, the ticket it to replace it with the new logo. If we don't have a version of the new logo that confirms to Facebook, Twitter, and LinkedIn (I think, I would have to look at what social meta tags we have) then ones will need to be made from the source. If we don't have a PSD (or whatever master format we used) then we will need to get that.
