### ISSUE TITLE
Initial page loading after starting service is slow

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#22]
After starting service with Docker (and likely in other situations) the initial page load is slow. Investigate and resolve. May require updating Dockerfile or adjusting development env settings.

**Comment by csjoblom** [comment]
https://stackoverflow.com/questions/16744279/rails-development-server-is-slow-and-takes-a-long-time-to-load-a-simple-page

**Comment by csjoblom** [comment]
#40 disables the config.asset.debug, I'd recommend those having issues with JS to re-enable this flag if they see issues. (if we want to accept this change)
