### ISSUE TITLE
Add "Include M-Lab data" filter to map filters (2 SP)

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#224]
**Is your feature request related to a problem? Please describe.**
Occasionally we would like to visualize only SUA data. This is extra important when viewing Census Blocks.

**Describe the solution you'd like**
Add a map filter that controls if M-Lab data is included in the data shown to users. The filter should be enabled (include M-Lab) by default and it should be a checkbox. When the checkbox is not checked, the map should only show SUA submissions (from_mlab=0 in the DB). Then the state of the checkbox changes the map should reload.

**Comment by noahbrenner** [comment]
Resolved by #271
