### ISSUE TITLE
Nightly Process Broken (2SP)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#230]
"Number of Tests Per ISP" graph about 3/4ths of the way down the page of https://speedupamerica.com/all-results is showing a decreased number of tests. The decrease is in the middle of November, which would seem to indicate that the issue started at that time. There is a nightly data update process, it is likely that it is that process that needs attention.

**Comment by ryanrolds** [comment]
The place to start is the CloudWatch logs on AWS, that is where the output from the nightly jobs get stored.

**Comment by ryanrolds** [comment]
My guess is that the M-Lab import may not be working.

**Comment by critzo** [comment]
Hi there SUA team. The issue with decreased test volume is a result of our recent platform transition to Docker/Kubernetes. In November specifically, once the FCC MBA program completed, the M-Lab team completed a series of upgrades to the remaining servers in the US. 

The old NDT server and ETL pipeline made data available in these BQ views:
- `measurement-lab.ndt.downloads`
- `measurement-lab.ndt.uploads`
- `measurement-lab.ndt.recommended`
- `measurement-lab.ndt.web100`

As of Nov. 20, 2019, all new NDT test data from the new NDT server is posting results to:
- `measurement-lab.ndt.ndt5`
- `measurement-lab.ndt.tcpinfo`

I have a blog post draft about this transition that I hope to publish early next week, but the impact is basically that we'll need to help with updated queries for SUA. To complicate things, currently the test data is in `ndt5` and the metadata is in `tcpinfo`, requiring a JOIN. 

Our team is still working on a "unified" table schema for ndt5, where geolocation and other annotated fields are all in the same table/view, which is likely to be done in early Q1. Once that is done, your queries will likely need another update.

I'll have a look at [these queries](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb) and put together a PR or diff next week to address the current issue.

**Comment by ryanrolds** [comment]
Was there a notice about the switch that we missed? Where do we need to be looking to catch breaking changes like this?

**Comment by ryanrolds** [comment]
One thing Production doesn't have is monitoring. If the data import process isn't working or we importing 0 records from M-Lab a notice should be sent to Slack. Without monitoring, we always going to catch these things weeks late.

**Comment by critzo** [comment]
@ryanrolds Unfortunately, there was not a notice explicitly about this impact of our platform transition. Our engineers have blogged about the transition generally, but not about the change in tables. This is totally on M-Lab and I apologize that there wasn't advanced notice. I'm bringing this to our team's attention. We need to establish a notification channel for downstream data users like SUA.

**Comment by critzo** [comment]
I've reviewed the current queries in [submissions_importer.rb](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/classes/submissions_importer.rb) and written the two queries below as replacements which use the new tables in their current state:

**Upload**
```
#standardSQL
SELECT
  ndt5.ParseInfo.TaskFileName AS test_id,
  TIMESTAMP_SECONDS(ndt5.log_time) AS UTC_date_time,
  ndt5.result.ClientIP AS client_ip,
  tcpinfo.Client.Geo.latitude AS client_latitude,
  tcpinfo.Client.Geo.longitude AS client_longitude,
  tcpinfo.Client.Geo.country_code AS country_code,
  tcpinfo.Client.Geo.region AS region,
  tcpinfo.Client.Geo.city AS city,
  tcpinfo.Client.Geo.postal_code AS postal_code,
  ndt5.result.C2S.MeanThroughputMbps AS uploadThroughput,
  NULL AS downloadThroughput,
  TIMESTAMP_DIFF(ndt5.result.C2S.EndTime, ndt5.result.C2S.StartTime, MICROSECOND) AS duration,
  tcpinfo.FinalSnapshot.TCPInfo.BytesReceived AS HCThruOctetsRecv,
  ndt5.result.C2S.UUID AS test_UUID
FROM
  `measurement-lab.ndt.ndt5` ndt5,
  `measurement-lab.ndt.tcpinfo` tcpinfo
WHERE
  ndt5.partition_date BETWEEN '#{start_date}' AND '#{end_date}'
  AND ndt5.result.C2S.UUID = tcpinfo.UUID
  AND tcpinfo.Client.Geo.country_code = '#{country_code}'
  AND tcpinfo.Client.Geo.region = '#{region}'
ORDER BY ndt5.partition_date ASC, ndt5.log_time ASC
```
**Download:**
```
#standardSQL
SELECT
  ndt5.ParseInfo.TaskFileName AS test_id,
  TIMESTAMP_SECONDS(ndt5.log_time) AS UTC_date_time,
  ndt5.result.ClientIP AS client_ip,
  tcpinfo.Client.Geo.latitude AS client_latitude,
  tcpinfo.Client.Geo.longitude AS client_longitude,
  tcpinfo.Client.Geo.country_code AS country_code,
  tcpinfo.Client.Geo.region AS region,
  tcpinfo.Client.Geo.city AS city,
  tcpinfo.Client.Geo.postal_code AS postal_code,
  ndt5.result.S2C.MeanThroughputMbps AS downloadThroughput,
  NULL AS uploadThroughput,
  TIMESTAMP_DIFF(ndt5.result.S2C.EndTime, ndt5.result.S2C.StartTime, MICROSECOND) AS duration,
  tcpinfo.FinalSnapshot.TCPInfo.BytesReceived AS HCThruOctetsRecv,
  ndt5.result.S2C.UUID AS test_UUID
FROM
  `measurement-lab.ndt.ndt5` ndt5,
  `measurement-lab.ndt.tcpinfo` tcpinfo
WHERE
  ndt5.partition_date BETWEEN '#{start_date}' AND '#{end_date}'
  AND ndt5.result.C2S.UUID = tcpinfo.UUID
  AND tcpinfo.Client.Geo.country_code = '#{country_code}'
  AND tcpinfo.Client.Geo.region = '#{region}'
ORDER BY ndt5.partition_date ASC, ndt5.log_time ASC
```

I've also received commitment from our dev team that the unified `ndt5` table/view will be completed by the end of January 2020.

**Comment by mattsayre** [comment]
Thank you for the updated queries Chris!

**Comment by Kourchenko** [comment]
Code merged. Will monitor nightly data imports.

**Comment by critzo** [comment]
Saw this get merged and wanted to ping with an update that our team is working now to complete the "unified" upload and download views, which I'm expecting in ~1 week. I'll be in touch with you as soon as that is ready. 

I also noticed in reviewing my queries above, that there's an error I didn't catch in the **download** query. This line in the WHERE statement: `AND ndt5.result.C2S.UUID = tcpinfo.UUID` should be `  AND ndt5.result.S2C.UUID = tcpinfo.UUID`

As you're monitoring data imports and aggregate data, please let us know if you find anything anomalous. We expect that measured speeds will increase for tests from ~mid-November and beyond, due in some part to our servers having updated kernels and TCP versions after the platform transition.
