### ISSUE TITLE
Document and integration switch required prior to Feb 2020

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#236]
All SUA related documents and integrations need removed from my accounts. Currently there are project documents on my Dropbox Paper account, which are Markdown and can copy and pasted elsewhere. There are likely integration between my GitHub account and AWS CodeBuild/CodePipeline, which will need to be reconfigured using someone else's account. There may also be integrations in Slack.

At the end of January I will be removing my account from this repo and org and will attempt to deactivate my TAO AWS account, if it hasn't been done already.

**Comment by mattsayre** [comment]
Per Ryan's request, I have created case with AWS to transfer site dependencies services from Ryan's account to my AWS account under the same org. In regards to the document migration, I will copy/paste into publicly available documents on the SUA Google Apps account.

**Comment by ryanrolds** [comment]
To ensure that all documents on Dropbox Paper are copied, I've add you (@mattsayre ) to the SUA folder in Paper.

**Comment by mattsayre** [comment]
Regarding Github > Slack integration, just read this KB article that says:

"If you use other Slack apps, you might notice some changes in the way GitHub is installed. This particular app functions at your workspace level, rather than at the member level. This is a good thing! Here's why:

The app will never disconnect should the original installer ever leave your workspace."

https://slack.com/help/articles/232289568-GitHub-for-Slack

**Comment by ryanrolds** [comment]
Then that may not be an issue.

**Comment by mattsayre** [comment]
@ryanrolds I was able to successfully "Move" all but two paper documents to a new folder. These two I didn't have the necessary permission on:
https://paper.dropbox.com/doc/SpeedUpAmerica-Data-NySR8sOYnUQCCB135eUTO
https://paper.dropbox.com/doc/SpeedUpAmerica-Infrastructure-q14UbYbhzyEM6mqaiN05d

**Comment by mattsayre** [comment]
AWS has advised that:
"So basically, after carefully  reviewing your account, I was able to see that the account that you mentioned has no active resources and the one that actually have them is yours.  So I would like to know if you can confirm which are the services that are supposed to be on the other account for me to see them and also to check which are the right steps to take. "

I looked at https://us-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines?region=us-west-2 and didn't see anything that was noted as associated with a specific user account explicitly.

**Comment by ryanrolds** [comment]
I have removed access to all Paper documents that I'm "owner" on. If they were not **copied** to a new account like I instructed in the original post then access may have been lost. If access needs to be restored so that you can copy them let me know.

**Comment by mattsayre** [comment]
Hi Ryan, there were just two documents that appeared to have different permissions than the rest:
https://paper.dropbox.com/doc/SpeedUpAmerica-Data-NySR8sOYnUQCCB135eUTO
https://paper.dropbox.com/doc/SpeedUpAmerica-Infrastructure-q14UbYbhzyEM6mqaiN05d

If Edit permissions can be granted on those 2 documents, I can copy them over, like was done with the other 10. Thank you!

**Comment by ryanrolds** [comment]
I don't think you understand the difference between a move and a copy. The previous documents appeared to be moved and not copies as I'm still the "owner", which can't be transferred on a non-business account.

You need to actually create a new document and copy the contents so that you are the owner of the document.

**Comment by mattsayre** [comment]
Thank you Ryan. All 12 documents have been copied over to a new folder. I'll work on re-linking them into the wiki next.

**Comment by ryanrolds** [comment]
I've removed myself from the TAO AWS accounts, the GitHub repos, and the Hack4Cause GitHub org.
