### ISSUE TITLE
CSV export with Oregon Census Block identifier (2SP)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#238]
Chris Tamarin who is the State of Oregon's lead person at the Oregon Broadband Office reached out to SUA and introduced Gary Dunmore of the Strategic Networks Group (SNG). The State of Oregon has contracted with SNG on a statewide broadband assessment, which looks at a number of factors including actual on the ground speed. SNG has asked for our Oregon data with the geocode attribute included. Right now the way I believe it works is that we only share granularity down to zip code and Census Tract, even though we capture geo accuracy down to the Census Block level. So the hope would be that we could export a CSV that included a column for Census Block where we have it.

**Comment by ryanrolds** [comment]
The lat+long accuracy information should be included, even if the lat+long isn't sent for privacy reasons.
