### ISSUE TITLE
Delete GitHub link from homepage

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#250]
## Updated solution

* Remove the following text from its current location on the homepage:
  > Questions about speedupamerica.com? Find more information here.
* Add the following text at the bottom of the page (possibly in the footer so that it's on every page?):
  > This website is an open source project which is always open to new contributors. To join in, visit [SpeedUpAmerica on GitHub](https://github.com/Hack4Eugene/SpeedUpAmerica/).

## Original issue description

**This issue was split off from #233 to reduce its scope.**

From @alexandracorvello:
> [...] get rid of the [text on the home page,] "Questions about speedupamerica.com? Find more information here." [...] That link to GitHub has been included in the FAQs page. Thank you!

The text to remove is below the "Take the Test!!" button and above the partner links.

**Comment by noahbrenner** [comment]
I think it makes sense to remove the text and link from that spot, but I'd also like to see a link to our GitHub repo directly from the home page.

The purpose I'm envisioning for the link would be different from that of the current text: Rather than being a place to get information on the project, it would be an invitation for people to contribute to our open-source project.

Maybe that link would belong on the very bottom of the page and have text something like "Contribute to SpeedUpAmerica on GitHub".

Thoughts?

**Comment by alexandracorvello** [comment]
Apologies about the late response, life has been a bit hectic since lane county declared a disaster emergency. I would put in something like “This website is powered by volunteers through GitHub, if you would like to help contribute to the SpeedUpAmerica website please go here (hyperlink) to help”  What do you think?

**Comment by noahbrenner** [comment]
No worries! I like your version being more explicit about the details and I wonder if we could be just as clear while making the text a little more concise. Maybe something like this?:

> This website is an open source project which is always open to new contributors. To join in, visit [SpeedUpAmerica on GitHub](https://github.com/Hack4Eugene/SpeedUpAmerica/).

**Comment by alexandracorvello** [comment]
That sounds good. I like your shortened version.

**Comment by noahbrenner** [comment]
Sounds great, I'll update the issue description.

**Comment by colindavey** [comment]
A couple of questions. 

1. There are five pages that have 

> Questions about speedupamerica.com? Find more information here.

Remove from all five? 

2. Is there currently a footer somewhere that is applied to all pages? If not, do we want to create one? I see that views/shared/_header.html.erb is used as a header over numerous pages. I don't see by what mechanism it is added to each page. But I think it might be through layouts/application.html.erb's `<%= render "shared/#{header_file_name}" %>.` But I don't see how `header_file_name` is associated with `views/shared/_header.html.erb`.

**Comment by colindavey** [comment]
Never mind, I think I got this.

**Comment by noahbrenner** [comment]
Resolved by #270
