### ISSUE TITLE
Census Blocks Added to Excel Export (1SP)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#260]
Builds off query created in support of previous ticket 243.

Incorporates this query into user accessible Excel export tool, which would then include census blocks/column in export file.

**Comment by mattsayre** [comment]
@Kourchenko any chance you have capacity to take a look at this one?

**Comment by Kourchenko** [comment]
@mattsayre PR created.
This definitely isn't worth 2SP. The code update is super simple. I'd be happy to lower it to 1SP to keep ticket work consistent for the amount of work required. 👍 :)

**Comment by mattsayre** [comment]
Okay, thank you very much @Kourchenko !

**Comment by Kourchenko** [comment]
Fixed.
