### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#27]
There are some inconsistencies in indentation style (different numbers of spaces or tabs), including for identical filetypes. Having an [.editorconfig](https://editorconfig.org/) file could help avoid future whitespace issues without contributors having to manually update their editor settings when editing different files. On the other hand, maybe we don't want yet another config file.

I'm happy to make a PR for this, just wanted to see if there was interest first.

If we do want such a file, we'll need to decide what conventions to establish with it.

**Comment by ryanrolds** [comment]
No objections. Please make sure the style matches the existing code as much as possible.

**Comment by noahbrenner** [comment]
I'm mostly seeing indentation of 2 spaces with the exception of `.md` files with 4 spaces.

---

In checking the indentation of various filetypes, I see that most are consistent, but JavaScript files have inconsistent indentation. I think this partly due to vendor scripts, which I don't think is an issue if we're not modifying them.

**Question 1:** I'm fairly certain the following files are generated at runtime by the server. They match a `.gitignore` rule, so I don't think they should be in the repo at all. Can we delete them?

```
public/assets/application-668d203e710c09a1e9de2cab3f0df39abb9343ad1c9c7e8fe05c987482529a5d.js
public/assets/application-f570e3c5ab3ef1decb9b203646db2fe1c379e8c240eb7aaaeb3202ac8cc1c629.js
```

**Question 2:** This file has mixed spaces and tabs. Should I leave it alone or reindent it to match our 2-space rule?

```
app/assets/javascripts/mlab.js
```
