### ISSUE TITLE
Restoring Zendesk .5 SP

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#272]
colindavey found a 404 with a zendesk integration, which lead to finding an expired zendesk account. A  new account was created with Zendesk. Our new support URL is speedupamericahelp.zendesk.com I think the integration was handled by what Zendesk calls a Web Widget and I just found that code:

<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=c0957b4c-a84a-43de-9ce3-965ad066e2ff"> </script>

This could be as simple as replacing the key, in the existing site code.

**Comment by colindavey** [comment]
Just to clarify, which of these do you think is the correct fix? 

`<script id="https://speedupamericahelp.zendesk.com"> </script>` 

`<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=speedupamericahelp.zendesk.com"> </script> `

`<script id="ze-snippet" src="https://speedupamericahelp.zendesk.com?key=c0957b4c-a84a-43de-9ce3-965ad066e2ff"> </script>`

**Comment by noahbrenner** [comment]
Resolved by #273
