### ISSUE TITLE
Increased geolocation accuracy in Excel export (SP 1)

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#278]
**Is your feature request related to a problem? Please describe.**
Broadband advocates are seeking grants to address the digital divide, prioritizing the most unserved/underserved locations. To do this, the most specific geolocation of speed test data is needed.

**Describe the solution you'd like**
The Excel document (via one click on the home page) from Speedupamerica.com is helpful in that it includes Zip Code, Census Tract, and Census Block geographic specificity. However what broadband advocates really want is the latitude and longitude level specificity. 

**Describe alternatives you've considered**
Already included in the report is Zip Code, Census Tract, and Census Block geographic specificity.

**Additional context**
In addition to lat and long, broadband advocates would also like to include "accuracy" value into Excel report. This value shows the relative accuracy of the lat/long based location.

**Comment by noahbrenner** [comment]
Closed by #280
