### ISSUE TITLE
move from ndt5 to ndt7

### ISSUE THREAD

**Issue by critzo** [Hack4Eugene/SpeedUpAmerica#279]
**Is your feature request related to a problem? Please describe.**
M-Lab is working to help as many third party integrations of NDT to migrate from ndt5 to ndt7. [ndt7-js](https://github.com/m-lab/ndt7-js) has undergone [recent testing and bug fixing](https://github.com/m-lab/ndt7-js/issues?q=is%3Aissue+is%3Aclosed).

**Describe the solution you'd like**
Transition speedupamerica to ndt7-js.

**Describe alternatives you've considered**
N/A

**Additional context**
Currently, SUA uses the following to provide the ndt5 test:
* [/vendor/assets/javascripts/ndt.js](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/vendor/assets/javascripts/ndt.js)
* [/app/assets/javascripts/ndt_speed_test.coffee](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/assets/javascripts/ndt_speed_test.coffee)
* [/app/assets/javascripts/ndt_d3.js](https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/assets/javascripts/ndt_d3.js) - ([d3.js](https://d3js.org/) front-end)

Replacing this with ndt7 will involve, but may not be limited to:
* Using [ndt7.js & related .js files](https://github.com/m-lab/ndt7-js/tree/main/src)
* Update `ndt_d3.js` with ndt7's response codes & callbacks
* Updating `ndt_speed_test.coffee` to use [Locate v2](https://locate.measurementlab.net/v2/nearest/ndt/ndt7) may not be needed since ndt7-js includes server discovery

**Comment by mattsayre** [comment]
Hey friends, just checking in on this issue. Any ETA on the move from ndt5 to ndt7?

**Comment by critzo** [comment]
@mattsayre apologies for my delayed reply. I'll resurface this internally in the upcoming week with @laiyi-ohlsen and @robertodauria. I'll also use the docs and spin up a local instance to test some ideas.

**Comment by laiyi-ohlsen** [comment]
Hi @mattsayre, @robertodauria will prioritize this to be completed within the next 1-2 weeks. Thanks for resurfacing!

**Comment by mattsayre** [comment]
Thank you for the support @laiyi-ohlsen and MLab.
