### ISSUE TITLE
Adjust Logic on Hero Button

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#28]
We need to adjust the logic in the Take Test button on the homepage, center, such that it consistently appears and supports the best services. 

From #20 

@noahbrenner :
There is a function called start_speed_test which sets a click listener on DOM elements with the test-speed-btn class. There are 3 such elements, but none of them are visible when visiting the homepage or after clicking the "Take the Test!!" button.

I'm wondering if these are left over from a previous implementation. We may be able to delete this function entirely as well as the elements it sets listeners for. If we do keep this function, I'd want to rename it to enable_speed_test since it only sets listeners, it doesn't actually kick off the test itself.

@ryanrolds providing extra context:

 When they agree to give us access to their location lets enable the button (or however it works). As they are taking the test we can get more accurate location information. Make sure to also use watchPosition(...) we can get the most accurate location we can. We will use whatever location we have when they submit.

**Comment by noahbrenner** [comment]
I think we can close this. By my reading, it's covering 2 things which are covered by more specific issues:

1. Make sure the "Take the Test" button is always enabled. This was covered by #20 and resolved in #37.
2. Improve choice of location services. This is covered by #29.

As for the `start_speed_test` function, I found that it *is* used. It enables the button on the last screen in the test process. That function was renamed to the more accurate `*enable*_speed_test` in #34.

Any objections to closing this issue?

**Comment by Amcclennahan** [comment]
Nope, closing!
