### ISSUE TITLE
Investigate/implement best location services in Speed Test

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#29]
There may be some inefficiencies and needless reliance on external services to get location data. 

Presently: We're getting location information (including address!?) from a service *before a test is even taken.* 

Future: Do we need an external service? Our location data retrieved from the test itself could be enough. If we do need that service, let's make sure it goes where it makes sense, say, during the test. 

From ticket #20 

As they are taking the test we can get more accurate location information. Make sure to also use watchPosition(...) we can get the most accurate location we can. We will use whatever location we have when they submit.

If for some reason we don't have a point when they submit their speed test we will probably need to wait until we do or error after some period of time (30 seconds?).

**Comment by mattsayre** [comment]
This issue has been resolved in another ticket.
