### ISSUE TITLE
Redesign Hero Elements in UI

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#30]
All of our designs should be in service of the following three priorities, in order:

1. Getting people to take the test.
2. Viewing the map of data
3. Raising awareness

That said, let's get the hero element to prominently display the "Take Test" button.

**Comment by Kourchenko** [comment]
Closing ticket until we begin officially being the frontend redesign.
Design mockups can be seen here: https://app.zeplin.io/project/5cf0bdb6e0ee93091a9b5c12/dashboard
