### ISSUE TITLE
Redesign below-the-fold on home page

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#31]
Clean up design below the fold. Remember our priorities.

1. Get Data.
2. Show data.
3. Raise awareness

Here is a doc that could be valuable for any copy needs:

https://bit.ly/2vjt4Zq

**Comment by Kourchenko** [comment]
Closing ticket until we begin officially being the frontend redesign.
Design mockups can be seen here: https://app.zeplin.io/project/5cf0bdb6e0ee93091a9b5c12/dashboard
