### ISSUE TITLE
Clean up the survey associated with the test (2SP)

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#32]
We want to make the survey achievable and attractive. This is squarely inside our number one priority, getting data. Too many required questions may muddy data. Here are a few things to consider to reduce barrier to entry:

Here are the stated requirements for the survey (that's not detected by the test itself):

1. Type of internet: cable, DSL, Broadband, etc
2. Current device internet connection: Wifi, Wired, Cellular
3. Advertised download speed
4. Advertised upload speed
5. Customer satisfaction
6. Monthly cost
7. Are you testing from work, home, or public?

**Comment by Amcclennahan** [comment]
@mattsayre I pulled these questions from the value prop document and I have a question:

Do we want each of these to be required fields? It opens us up for possible inaccuracies or fewer data points. That said, it's not a ton of questions so, if designed well, I don't necessarily think it's a deal breaker. My gut is saying don't require all of them -- only the essentials. If we do require all of them, I might suggest having advertised speeds and cost as ranges, and make none of them "fill in the blank" to secure data that's as accurate and easily acquired as possible. 

Thoughts?

**Comment by mattsayre** [comment]
@Amcclennahan yes, I think those are the questions that add a layer of new value on top of the speed test itself.
Type of Internet service: Dial Up, Satellite, Fiber, Cellular, DSL, Cable, Line of Sight, other _____
This device's Internet connection is: Wifi, Wired, Cellular, other _____
Advertised download speed based on user input.
Advertised upload speed based on user input.
Customer service satisfaction Negative, Neutral, or Positive?
What is your monthly cost for just the Internet portion of your bill?
Where are you testing from: Home or Mobile or Work/Public

**Comment by Amcclennahan** [comment]
Thanks for the guidance!

 @Kourchenko let me know if you have more questions.

**Comment by mattsayre** [comment]
This ticket now overlaps another, closing.
