### ISSUE TITLE
Get Census Tract boundaries and update task that loads them

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#4]
> For setup instructions look at [README.Docker.md](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/README.Docker.md). Once we have complete local environment setup instructions (a few tickets need to be finishing) we will update README.md.

Census Tract boundaries appear to be lazy loaded with a [rake task](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/lib/tasks/submissions.rake#L21) that run automatically [Mondays at 11:30pm](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/config/schedule.rb#L25). Try running the task with `docker-compose run frontend rake update_pending_census_codes`. This task may still work and will require having at least 1 speed test (submission) in the database.

Lazy loading Census Tracts is undesirable; We want to update our map/stats faster and discover bottlenecks sooner rather than later. We need to preload all the Census Tracts for Lane County. Locate a source for the boundaries (check with Matt Sayre, he was talking to County/City, or find a free source online) and update the task to load from the file. Remove automatic running of the task. Host the data file somewhere (S3, Dropbox, Google Drive), we will sort out the final location later. Update README.Docker.md with instructions for downloading and loading the data.

The boundary data loaded in the database appears to be an array of lat+long pairs and should look like [[lat1,long1],[lat2,long2],...,[latN, longN]]. See the code and DB schema for more details.

**Comment by Amcclennahan** [comment]
Focus on #3 If not completed or taken yet

**Comment by Amcclennahan** [comment]
I see this got assigned on Sunday, @bishoplafer @csjoblom did it end up getting completed?
