### ISSUE TITLE
Simplify JS control flow, eliminating duplicate work

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#48]
The files `home.coffee` and `ndt_speed_test.coffee` (under `app/assets/javascripts/`) have some interaction and overlapping purposes, but they are written in different styles, duplicate some work, and coordinate in an awkward way. We should clean this up when we get a chance.

* **Different styles:** `home.coffee` uses jQuery's `.ajax` method. `ndt_speed_test.coffee` uses `XMLHttpRequest` directly. As long as we're bundling jQuery, we might as well use it.
* **Duplicate work:** Both files call `navigator.geolocation.getCurrentPosition()` and call different API endpoints with the result. They both set the value of the hidden form fields `#submission_latitude` and `#submission_longitude`, though this specific duplication may be removed if #45 is merged.
* **Awkward coordination:** Right now, `ndt_speed_test.coffee` sets a click listener on a hidden form field (`#start_ndt_test`) which starts the speed test. Later, `home.coffee` simulates a click event (`.click()`) on that hidden field in order to kick off the test. I don't see a good reason to touch the DOM for this; we should just be able to call the correct function directly after importing one file into the other (I don't know whether this would be a coffeescript feature or a ruby feature).

**Comment by mattsayre** [comment]
My understanding is that these have been cleaned. The word was done incrementally in other PR's.
