### ISSUE TITLE
Estimate AWS cost for Test and Production environments

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#5]
When trying to get AWS credits, they asked that we provide an estimate using their calculator.

We need a Test and Production environment. The Test env can be small as it's only used by contributors for integration testing and demos. The Production environment will need to handle a yet to be determined amount of load for the county-level and state-level milestones. 

### Test (US-West-1)
* MySQL RDS - Single-AZ T3 Medium w/ 16GB GP SSD EBS
* ECS - 2 x EC2 T3 Small w/ 16GB GP SSD EBS each
* Application LB for ECS
* 1 GB of S3
* VPC

### Production (US-West-1)
* MySQL RDS - Single-AZ T3 Medium w/ 16GB GP SSD EBS
* ECS - 3 x EC2 T3 Small w/ 16GB GP SSD EBS each
* Application LB for ECS
* 1 GB of S3
* VPC

### Shared
* Domain on Route53

The DB doesn't need to be Mulit-AZ to start, but if the project gets any kind of traction and we care about uptime, we will need to move to a Multi-AZ MySQL RDS instance. The above uses General Purpose SSD, which under load may not provide the IO performance required. Before reaching a state-level amount of load we may need to upgrade to Provisioned SSD.

We assume we only need T3 Smalls for the Frontend servers. but depending on the memory footprint we may need to upgrade to T3 Mediums. The amount of EBS space required for the DBs and Frontend may also grow, but EBS is cheap so not a huge concern. As load increases, we will want to add additional EC2 instances to ECS. We have no way to reliably predict growth in load until we have more insight into the services real-work performance. 

Use the [AWS calculator](https://calculator.s3.amazonaws.com/index.html) to determine the cost of the environments. Determine the increase in cost if must use T3.Mediums instead of Smalls.

> If anyone has comments, concerns, or feedback on the above requirements please comment.

**Comment by mattsayre** [comment]
First pass at this is $320.50/month. 

For DB’s, assumed On-Demand.
For data transfers, made no assumptions.

https://calculator.s3.amazonaws.com/index.html#key=calc-BBCE25D6-9E59-41AC-B7C5-F15FE55072CB&r=SFO

**Comment by ryanrolds** [comment]
Looking over the details, I don't think we need the VPN Connections for the VPC. Vanilla VPCs may not cost anything.

**Comment by mattsayre** [comment]
Revised without VPN is $247.30/month
https://calculator.s3.amazonaws.com/index.html#key=calc-1E39D743-C92D-4FDB-B4F1-552AF01AA37D&r=SFO

Reference pricing for T3 Mediums upgrade is $338.05/month

Going to submit the $247.30/month link for credits.

**Comment by ryanrolds** [comment]
Looks good to me. Thanks @mattsayre.
