### ISSUE TITLE
Draw Empty Polygons in Areas without Data

### ISSUE THREAD

**Issue by khutchison** [Hack4Eugene/SpeedUpAmerica#50]
![image](https://user-images.githubusercontent.com/6693683/56920586-73077880-6a78-11e9-95ae-80f4d5aac697.png)

most of the map isn't grouped into any census track, tested from my home network, tried multiple refreshes

**Comment by ryanrolds** [comment]
That's just where we have data. It would probably we worth drawing empty polygons where we don't have data.

**Comment by khutchison** [comment]
Sounds good, I'll work on that over the weekend and see if I can figure it out

**Comment by mattsayre** [comment]
With vector tile sets the statistical boundaries are more clear and additional outlines are no longer needed.
