### ISSUE TITLE
Static Providers Replacement with DB Data Fixes

### ISSUE THREAD

**Issue by benanamen** [Hack4Eugene/SpeedUpAmerica#52]
File: app/views/home/_form_step_2a.html.erb
File app/views/home/_form_step_2b.html.erb

Same procedure both files...

**REPLACE lines 6-8 with...**
```
      <div class="col-md-offset-6 col-md-5">
        <%= select_tag :provider, options_for_select(get_providers_list), { class: 'chosen-select filter',  data: { placeholder: 'Select Client ISP to view' } } %>
        <%= hidden_field_tag :selected_provider %>
      </div>
```

**Comment by benanamen** [comment]
**FIX 2**
To add Provider name sorting in all places displaying Provider names add the following line to file app/models/provider_statistic.rb right after line 11, and before 'end'. This will conclude eliminating static provider data. All provider updates will now be done in the DB.

`  default_scope { order(name: :asc) }`

**Comment by benanamen** [comment]
Update on hold as a result of last nights meeting to focus on issues currently in Trello.

**Comment by ryanrolds** [comment]
Fixed.
