### ISSUE TITLE
Get "all" as a filter working consistently

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#56]
The "all" filter works unreliably right now. I've only gotten it to work once, here were the steps I took. On further attempts of the same process, I could not replicate.

1. Instigate map loading to get blank map
2. select filters (more than one)
3. Remove filters
4. Add "all" filter

Any other iteration of attempts were a failure to get all of the results to load.

**Comment by ryanrolds** [comment]
Fixed.
