### ISSUE TITLE
Make Data Exploration Fields Editable

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#57]
![Data Exploration tool brokent](https://user-images.githubusercontent.com/19477333/57003656-26599580-6b7d-11e9-8248-87e6936e5018.jpg)

These fields do not seem editable. 

As another option, we could deprecate these fields and roll the data exploration into the map explorer above. Having two sets of the same fields seems redundant.

**Comment by ryanrolds** [comment]
PR for this pending approval.
