### ISSUE TITLE
Combine "Measuring Internet Service in America" with "About SpeedUpAmerica"

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#58]
Below the fold, we have a section titled "Measuring Internet Service in America", then the Data Exploration, then a section with the same graphic titled "About SpeedUpAmerica"

Let's combine these at the bottom of the page. 
[
Header: About SpeedUpAmerica

The SpeedUpAmerica project is designed to help Americans understand the quality and cost of internet service provided to our citizens. By answering a few questions, you can help increase transparency around internet speeds and costs for residents. We DO NOT collect personal data in any way, shape, or form. We do ask for your location to help determine if there are areas of America that are consistently experiencing slow internet speeds.

Through www.speedupamerica.com and www.measurementlab.net/tools/ndt, Americans have submitted over 11196 internet speed tests to help improve internet service in each city!
]

**Comment by Amcclennahan** [comment]
If we manage this along with combining data exploration fields with map selector in #57, we can really clean up the front page and get rid of a lot of redundancy prior to our redesign efforts.

**Comment by ryanrolds** [comment]
Do we want to also include the section on the home page?

**Comment by Amcclennahan** [comment]
I guess we may as well. I don't see any harm in displaying the map on the homepage, below the take test and view map buttons. Then view map just needs to initiate a scroll to the map. 

This is fairly minor and if we get to it before June 7th, we may as well do that, but if it's after, the site is getting a redesign anyway so I don't see much point.

**Comment by ryanrolds** [comment]
Done.
