### ISSUE TITLE
ISP without tests causing map to stick on loading

### ISSUE THREAD

**Issue by Amcclennahan** [Hack4Eugene/SpeedUpAmerica#59]
Looks like the map sticks on loading if a user selects an ISP with no results in certain situations. 

An empty map will display if there are no tests submitted within a date range. 

Steps to reproduce:

1. Navigate to Map
2. Choose "Charter Communications" as an ISP
3. Leave the date range as default, or choose a date range that certainly has submissions.

**Comment by ryanrolds** [comment]
Fxied.
