### ISSUE TITLE
Create new design for SpeedUpAmerica

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#6]
The current design will be acceptable in the short-term, but we need to begin iterating on a revamped UX for a national level solution. This ticket is mostly a place to collect ideas, we don't yet have a clear set of UX requirements.

**Comment by ryanrolds** [comment]
https://app.zeplin.io/project/5cf0bdb6e0ee93091a9b5c12/dashboard

**Comment by JCoulter85** [comment]
I might be able to aid with this. With my experience as a digital content creator I can create several different designs to choose from. I would like to discuss this topic and brain storm ideas.

**Comment by mattsayre** [comment]
This is already in progress outside of Github. Matt will talk with Bishop and Santiago to recognize Story Point distribution.
