### ISSUE TITLE
QA Before You Start Wiki page

### ISSUE THREAD

**Issue by antonioortegajr** [Hack4Eugene/SpeedUpAmerica#64]
A page for all looking to add to the project is needed. This wiki entry should be a front loader for anyone thinking about adding to this project. https://github.com/Hack4Eugene/SpeedUpAmerica/wiki/Before-You-Start

QA all links, spelling, comment in this issue with any resources that may be missing.

**Comment by benanamen** [comment]
Suggested edits:
First this, thank you for wanting to help on this project and bringing your skills to this _**project**_.
*Needs space...projects here
This project is team first. Check out the current team **_projectshere_** also 

Missing link??
also see the **_[https://github.com/Hack4Eugene/SpeedUpAmerica/issues]_**(issues being worked on).

**Comment by antonioortegajr** [comment]
made suggested edits with exception of the project manager as that could change in the future. We might want a separate doc for roles and contacts? Not everyone might want to be contacted. Added a tutorial on ubuntu in the docker for windows wiki page.
