### ISSUE TITLE
results page missing some logos

### ISSUE THREAD

**Issue by nohorse** [Hack4Eugene/SpeedUpAmerica#69]
![image](https://user-images.githubusercontent.com/311063/57238295-ef9cd880-6fdd-11e9-847e-98a0c3bf8c2e.png)

**Comment by ryanrolds** [comment]
Good catch.

**Comment by ryanrolds** [comment]
@Amcclennahan Can we get a 1SP task for this?

**Comment by Amcclennahan** [comment]
done!
