### ISSUE TITLE
In UI replace Louisville/SpeedUpYourCity with Lane County/SpeedUpAmerica

### ISSUE THREAD

**Issue by ryanrolds** [Hack4Eugene/SpeedUpAmerica#7]
The plan is to rebrand under SpeedUpAmerica. As we will not be launching with a national dataset, we need to focus the map on Lane County. Go through the UI with a fine-toothed comb and replace all references to Louisville/SpeedUpYourCity with SpeedUpAmerica. The map must center on Lane County.

> For setup instructions look at [README.Docker.md](https://github.com/Hack4Eugene/SpeedUpYourCity/blob/master/README.Docker.md). Once we have complete local environment setup instructions (a few tickets need to be finishing) we will update README.md.

**Comment by ryanrolds** [comment]
https://github.com/Hack4Eugene/SpeedUpAmerica/pull/8

**Comment by Kourchenko** [comment]
UI fixes:
- Replaced several instances of SpeedUpYourCity with SpeedUpAmerica.
- Fixed Partnerships to reflect the companies that are partners with this project (TAO, US Ignite, M-Lab).
- Fixed Partnerships logos, removed previous company logos, added new company logos.

**Comment by ryanrolds** [comment]
Great work. Thanks @Kourchenko
