### ISSUE TITLE
Updated fancy Logo!

### ISSUE THREAD

**Issue by nohorse** [Hack4Eugene/SpeedUpAmerica#70]
Our current logo is pretty good.  
![image](https://user-images.githubusercontent.com/311063/57416820-9a67ef00-71b6-11e9-9352-7ed6a3ecf22f.png)

But we could go for something fancier!

Please comment below with some logo ideas and we'll have a discussion.  

this is the plan:
- [ ] post your ideas
- [ ] we'll chat about them
- [ ] pick a winner
- [ ] do the work
- [ ] close the issue

**Comment by ryanrolds** [comment]
@Kourchenko @bishoplafer @csjoblom. Ideas? Also, is Cory in the H4AC org?

**Comment by nohorse** [comment]
this ticket was just a sample from the #mozsprint event last night.  closing now
