### ISSUE TITLE
Group by Census Block

### ISSUE THREAD

**Issue by mattsayre** [Hack4Eugene/SpeedUpAmerica#77]
In rural geographies, zip codes boundaries and census tract boundaries can inadvertently group divergent internet availability types. This can lead to, for example, a median download speed metric that doesn't accurately reflect the on the ground truth. Smaller geographic boundaries are needed. A logical next unit of filter is a Census Block.

**Comment by ryanrolds** [comment]
There are a lot of Census Blocks in Oregon and Lane County, more than we can deliver to the browser quickly. We also need to get the Census Block boundaries. This will very likely require vector tilsets.

**Comment by ryanrolds** [comment]
Blocked until we have vector tilesets and the ability to do point-in-polygon lookups

**Comment by mattsayre** [comment]
Census blocks are going to be part of the on-request reporting service and not something we plan to take on with the publicly facing map at this time.
